pretext: A clear path to help you “Design” in Digital World!
title: CE201
description: Amirkabir University of Technology Logic Circuit Design Course
university: Amirkabir University of Technology (Tehran Polytechnic)
course: Logic Circuit Design Course
authors: Reza Adinepour, NONE

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+
