pretext:            A clear path to help you “advance” in programming
title:              SUTAP
university:         Sharif University of Technology
course:             Advanced Programming course


# Social Profiles
twitter_username:
github_username:    advprog2020
facebook_username:
instagram_username:
linkedin_username: