pretext:            A clear path to help you “advance” in programming
title:              SUTAP
description:        Sharif University of Technology Advanced Programming course
university:         Sharif University of Technology
course:             Advanced Programming course



course_videos:    80+   
course_duration:  72
course_students:  170+
course_TAs:       45
course_lessons:   20
course_resourses: 40+