pretext: A Clear Path to Help You “Design” In Logic World!!!!!
title: CE201
description: Amirkabir University of Technology Digital Logic Design Course
university: Amirkabir University of Technology
course: Digital Logic Design Course
authors: Reza Adinepour

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+
