pretext: A clear path to help you “Design” in Digital World!
title: AUTDD
description: Amirkabir University of Technology Digital Design course
university: Amirkabir University of Technology
course: Digital Design course
authors: Reza Adinepour, NONE

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+
