title:              SUTAP
email:              ahsa9978@gmail.com
description:        Github Page of Sharif University of Technology Advanced Programming course
author:             Ahmad Salimi, Hamila Mailee
baseurl:            "/docs"
url:                "https://advprog2020.github.io/"

# Social Profiles
twitter_username:
github_username:    advprog2020
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-EYD2ZBQXLK # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
