pretext:            A clear path to help you “advance” in programming
title:              SUTAP
description:        Sharif University of Technology Advanced Programming course
university:         Sharif University of Technology
course:             Advanced Programming course



course.videos:    80+   
course.duration:  72
course.students:  170+
course.TAs:       45